# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Nexys4DDR_C.xdc

# IP: ip/ddr/ddr.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# IP: ip/ClkGen/ClkGen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] -quiet

# XDC: /home/bogdan/Facultate/AN3/SSC/Project/ssc-vhdl-project/vhdl-project/vhdl-project.gen/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# XDC: /home/bogdan/Facultate/AN3/SSC/Project/ssc-vhdl-project/vhdl-project/vhdl-project.gen/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc

# XDC: /home/bogdan/Facultate/AN3/SSC/Project/ssc-vhdl-project/vhdl-project/vhdl-project.gen/sources_1/ip/ClkGen/ClkGen_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/bogdan/Facultate/AN3/SSC/Project/ssc-vhdl-project/vhdl-project/vhdl-project.gen/sources_1/ip/ClkGen/ClkGen.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/bogdan/Facultate/AN3/SSC/Project/ssc-vhdl-project/vhdl-project/vhdl-project.gen/sources_1/ip/ClkGen/ClkGen_ooc.xdc
