# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/constraints/Nexys4DDR_C.xdc

# IP: D:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/BRAM_1/BRAM_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_1 || ORIG_REF_NAME==BRAM_1} -quiet] -quiet

# IP: D:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/PxlClkGen/PxlClkGen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PxlClkGen || ORIG_REF_NAME==PxlClkGen} -quiet] -quiet

# IP: D:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/Square_Root/Square_Root.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Square_Root || ORIG_REF_NAME==Square_Root} -quiet] -quiet

# IP: D:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ddr/ddr.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# IP: D:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ClkGen/ClkGen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/BRAM_1/BRAM_1_ooc.xdc

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/PxlClkGen/PxlClkGen_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PxlClkGen || ORIG_REF_NAME==PxlClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/PxlClkGen/PxlClkGen.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PxlClkGen || ORIG_REF_NAME==PxlClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/PxlClkGen/PxlClkGen_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PxlClkGen || ORIG_REF_NAME==PxlClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/PxlClkGen/PxlClkGen_ooc.xdc

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ddr/ddr/user_design/constraints/ddr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ClkGen/ClkGen_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ClkGen/ClkGen.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FACULTATE/An3/SSC/GIPO-ADVANCED/Nexys-4-DDR-OOB/src/ip/ClkGen/ClkGen_ooc.xdc
